const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const assert = require('assert');

console.log('=== TEST: Prometheus Target Generator Engine ===');

// Mock data
const mockDevices = [
  {
    ip: '192.0.2.10',
    name: 'SW-CORE-01',
    type: 'switch',
    vendor: 'Cisco',
    model: 'Catalyst1300-24P-4G',
    location: 'Main-DC',
    community: 'public',
    module: 'if_mib',
    enabled: true
  },
  {
    ip: '192.0.2.20',
    name: 'SW-ACC-01',
    type: 'coreswitch',
    vendor: 'Cisco',
    model: 'Catalyst9200L-24P',
    location: 'Building-1',
    community: 'public',
    module: 'if_mib',
    enabled: true
  },
  {
    ip: '192.0.2.99',
    name: 'Disabled-Dev',
    type: 'switch',
    enabled: false
  },
  {
    ip: '192.0.2.88',
    name: 'Deleted-Dev',
    type: 'switch'
  }
];

const mockDeletedIps = ['192.0.2.88'];

// 1. Test getActiveDevices
function getActiveDevices(db) {
  const deletedSet = new Set((db.deletedIps || []).map(ip => String(ip).trim()));
  return (db.devices || []).filter(d => {
    if (!d || !d.ip || typeof d.ip !== 'string') return false;
    const ip = d.ip.trim();
    if (!ip) return false;
    if (deletedSet.has(ip)) return false;
    if (d.enabled === false || d.disabled === true || d.status === 'disabled') return false;
    return true;
  });
}

const active = getActiveDevices({ devices: mockDevices, deletedIps: mockDeletedIps });
console.log('Active devices count:', active.length);
assert.strictEqual(active.length, 2, 'Should only have 2 active devices (filtering deleted and disabled)');
assert.strictEqual(active[0].ip, '192.0.2.10');
assert.strictEqual(active[1].ip, '192.0.2.20');
console.log('✓ getActiveDevices test passed');

// 2. Test generateTargetsYaml
function generateTargetsYaml(activeDevices, defaultSettings = {}) {
  if (!activeDevices || activeDevices.length === 0) {
    const emptyYaml = "# Auto-generated by NetMonitor Backend Server (empty target list)\n[]\n";
    return {
      blackboxYaml: emptyYaml,
      snmpYaml: emptyYaml,
      targetCount: 0,
    };
  }

  let blackboxYaml = `# Auto-generated by NetMonitor Backend Server\n# Job: blackbox-icmp\n- targets:\n`;
  activeDevices.forEach(d => {
    blackboxYaml += `    - '${d.ip.trim()}'\n`;
  });
  blackboxYaml += `  labels:\n    job: 'blackbox-icmp'\n    module: 'icmp'\n`;

  const defaultMod = defaultSettings.defaultModule || 'if_mib';
  const defaultAuth = defaultSettings.defaultCommunity || 'public';

  let snmpYaml = `# Auto-generated by NetMonitor Backend Server\n# Job: snmp\n`;
  activeDevices.forEach(d => {
    const ip = d.ip.trim();
    const mod = d.module || defaultMod;
    const auth = d.community || defaultAuth;
    const safeName = (d.name || ip).replace(/['"\\]/g, '');
    const safeType = (d.type || 'switch').replace(/['"\\]/g, '');
    const safeVendor = (d.vendor || '').replace(/['"\\]/g, '');
    const safeLocation = (d.location || '').replace(/['"\\]/g, '');

    snmpYaml += `- targets:\n    - '${ip}'\n`;
    snmpYaml += `  labels:\n`;
    snmpYaml += `    job: 'snmp'\n`;
    snmpYaml += `    target: '${ip}'\n`;
    snmpYaml += `    module: '${mod}'\n`;
    snmpYaml += `    auth: '${auth}'\n`;
    if (safeName) snmpYaml += `    name: '${safeName}'\n`;
    if (safeType) snmpYaml += `    type: '${safeType}'\n`;
    if (safeVendor) snmpYaml += `    vendor: '${safeVendor}'\n`;
    if (safeLocation) snmpYaml += `    location: '${safeLocation}'\n`;
    snmpYaml += `\n`;
  });

  return {
    blackboxYaml,
    snmpYaml,
    targetCount: activeDevices.length,
  };
}

const targets = generateTargetsYaml(active, { defaultModule: 'if_mib', defaultCommunity: 'public' });
console.log('\n--- Generated Blackbox YAML ---');
console.log(targets.blackboxYaml);

console.log('--- Generated SNMP YAML ---');
console.log(targets.snmpYaml);

assert(targets.blackboxYaml.includes("job: 'blackbox-icmp'"));
assert(targets.blackboxYaml.includes("module: 'icmp'"));
assert(targets.blackboxYaml.includes("- '192.0.2.10'"));
assert(!targets.blackboxYaml.includes("Disabled-Dev"));

assert(targets.snmpYaml.includes("job: 'snmp'"));
assert(targets.snmpYaml.includes("module: 'if_mib'"));
assert(targets.snmpYaml.includes("auth: 'public'"));
assert(targets.snmpYaml.includes("name: 'SW-CORE-01'"));
console.log('✓ generateTargetsYaml test passed');

// 3. Test Empty Target List (Requirement 8)
const emptyTargets = generateTargetsYaml([], {});
console.log('\n--- Empty Targets YAML ---');
console.log(emptyTargets.blackboxYaml);
assert.strictEqual(emptyTargets.blackboxYaml.trim(), '# Auto-generated by NetMonitor Backend Server (empty target list)\n[]');
assert.strictEqual(emptyTargets.snmpYaml.trim(), '# Auto-generated by NetMonitor Backend Server (empty target list)\n[]');
assert.strictEqual(emptyTargets.targetCount, 0);
console.log('✓ Empty target list test passed');

// 4. Test Mutex Concurrency
let isSyncing = false;
let syncQueued = false;
let executionCount = 0;

async function mockSyncTargets(tag) {
  if (isSyncing) {
    syncQueued = true;
    console.log(`[Mutex] Request ${tag} queued because another sync is in progress`);
    return;
  }
  isSyncing = true;
  try {
    do {
      syncQueued = false;
      executionCount++;
      console.log(`[Mutex] Executing sync pass #${executionCount} (triggered by ${tag})`);
      await new Promise(r => setTimeout(r, 20)); // simulate disk write & reload
    } while (syncQueued);
  } finally {
    isSyncing = false;
  }
}

async function runMutexTest() {
  console.log('\n--- Running Mutex Concurrency Test ---');
  // Fire 5 requests nearly simultaneously
  await Promise.all([
    mockSyncTargets('req1'),
    mockSyncTargets('req2'),
    mockSyncTargets('req3'),
    mockSyncTargets('req4'),
    mockSyncTargets('req5')
  ]);
  console.log(`Total actual sync executions for 5 rapid requests: ${executionCount}`);
  assert(executionCount <= 2, 'Should coalesce multiple parallel syncs to at most 2 executions');
  console.log('✓ Mutex concurrency test passed');
  console.log('\nALL UNIT TESTS PASSED SUCCESSFULLY! 🎉');
}

runMutexTest();
